import { Injectable } from '@angular/core';
import { HttpClient, HttpHandler, HttpHeaders } from '@angular/common/http';
import { catchError, Observable, of, throwError } from 'rxjs';
import { TickerDTO } from '../../ticker.model';

export interface StockEntity {
  id: string;
  estaEmSetorPerene: boolean;
  estaForaDeRecuperacaoJudicial: boolean;
  possuiBomNivelRetornoSobrePatrimonio: boolean;
  possuiBomNivelCrescimentoLucroNosUltimos5Anos: boolean;
  possuiBomNivelMargemLiquida: boolean;
  possuiBomNivelMargemEbit: boolean;
  possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: boolean;
  possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: boolean;
  possuiBomPrecoEmRelacaoAoValorPatrimonial: boolean;
  possuiNegociacaoAtiva: boolean;
  nomeEmpresa: string;
  segmentoEmpresa?: string; // Optional, as not all stocks have it
  score?: string; // Optional, as not all stocks have it
}

@Injectable({
  providedIn: 'root'
})
export class SimpleAnalisysService {

  isProd: boolean = true;
  hasBackend: boolean = false;

  private localDataPath = 'assets/stock-analisys-br.stocks.json'; // Path to local JSON file

  private baseUrlProd = "http://ec2-98-81-214-97.compute-1.amazonaws.com:8888/stock/analisys";
  private baseUrlProdOld = "https://analisys-brazilian-stock-36da1af9e42b.herokuapp.com/stock/analisys";
  private baseUrlDev = "http://localhost:8888/stock/analisys";

  constructor(private http: HttpClient) { }

  headerDict = {
    'Content-Type': 'application/json',
    'Accept': '*',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': '*',
    'Access-Control-Allow-Headers': '*'
  }

  requestOptions = {
    headers: new HttpHeaders(this.headerDict),
  };

  getAnalisys(ticker: string): Observable<any> {
    const baseUrl = this.isProd ? this.baseUrlProd : this.baseUrlDev;
  
    if (this.hasBackend) {
      return this.http.get(`${baseUrl}/${ticker}`, this.requestOptions).pipe(
        catchError((error) => {
          console.error('Error fetching analysis:', error);
          return throwError(() => new Error('Failed to fetch analysis data. Please try again later.'));
        })
      );
    }
  
    // Wrap the filtered result in an observable
    const result = stocks.find(stock => stock.id === ticker);
    return of(result);
  }
  

  getTickers(): TickerDTO[] {
    return this.allTickers
      .filter(it => it[0].slice(-1).includes("3") || it[0].slice(-1).includes("4"))
      .map(it => new TickerDTO(it[0], it[1].replace("- ", "").toUpperCase()))
      .sort(function (a, b) {
        let first = a.description.toLowerCase();
        let second = b.description.toLowerCase();
        return first < second ? -1 : first > second ? 1 : 0;
      })
  }

  getTickersMostTraded() {
    return this.allTickers.map(ticker => ticker[0]);
  }

  // Function to replace tickers ending in '4' or '11' with '3'
  replaceTickers(tickers: [string, string][]): [string, string][] {
    return tickers.map(([ticker, name]) => {
      if (ticker.endsWith('4') || ticker.endsWith('4F') || ticker.endsWith('11')) {
        ticker = ticker.substring(0, ticker.length - 1) + '3';
      }
      return [ticker, name];
    });
  }


  //Top 100 companies most traded
  allTickers: [string, string][] = [
    ['ABEV3', ' - AMBEV S/A'],
    ['AERI3', ' - AERIS'],
    ['AZUL4', ' - AZUL'],
    ['B3SA3', ' - B3'],
    ['BBAS3', ' - BANCO DO BRASIL'],
    ['BBDC3', ' - BANCO BRADESCO'],
    ['BBSE3', ' - BB SEGURIDADE'],
    ['BEEF3', ' - MINERVA'],
    ['BPAC3', ' - BTGP BANCO'],
    ['BRAP3', ' - BRADESPAR'],
    ['BRDT3', ' - PETROBRAS DISTRIBUIDORA'],
    ['BRFS3', ' - BRF'],
    ['BRKM3', ' - BRASKEM'],
    ['BRML3', ' - BR MALLS'],
    //['BTOW3', ' - B2W'],
    ['CARD3', ' - CSU CARDSYSTEM'],
    ['CCRO3', ' - CCR'],
    ['CESP3', ' - CESP'],
    ['CGRA3', ' - GRAZZIOTIN'],
    //['CIEL3', ' - CIELO'],
    ['CMIG3', ' - CEMIG'],
    ['COGN3', ' - COGNA'],
    ['CPFE3', ' - CPFL ENERGIA'],
    ['CPLE3', ' - COPEL'],
    ['CRFB3', ' - CARREFOUR BRASIL'],
    ['CSAN3', ' - COSAN'],
    ['CSMG3', ' - COPASA'],
    ['CSNA3', ' - SID NACIONAL'],
    ['CVCB3', ' - CVC BRASIL'],
    ['CYRE3', ' - CYRELA'],
    ['DASA3', ' - DASA'],
    ['DIRR3', ' - DIRECIONAL'],
    ['DTEX3', ' - DURATEX'],
    ['ECOR3', ' - ECORODOVIAS'],
    ['EGIE3', ' - ENGIE BRASIL'],
    ['ELET3', ' - ELETROBRAS'],
    ['EMBR3', ' - EMBRAER'],
    ['ENEV3', ' - ENEVA'],
    ['ENGI3', ' - ENERGISA'],
    ['EQTL3', ' - EQUATORIAL'],
    ['EZTC3', ' - EZTEC'],
    ['FLRY3', ' - FLEURY'],
    ['GGBR3', ' - GERDAU'],
    ['GNDI3', ' - INTERMÉDICA'],
    ['GOAU3', ' - GERDAU MET'],
    ['HAPV3', ' - HAPVIDA'],
    ['HGTX3', ' - CIA HERING'],
    ['HYPE3', ' - HYPERA'],
    ['IGTA3', ' - IGUATEMI'],
    ['IRBR3', ' - IRB BRASIL'],
    ['ITSA3', ' - ITAUSA'],
    ['ITUB3', ' - ITAU UNIBANCO'],
    ['JBSS3', ' - JBS'],
    ['KLBN3', ' - KLABIN S/A'],
    ['LAME3', ' - LOJAS AMERIC'],
    ['LCAM3', ' - LOCAMERICA'],
    ['LEVE3', ' - METAL LEVE'],
    ['LIGT3', ' - LIGHT S/A'],
    //['LINX3', ' - LINX'],
    ['LREN3', ' - LOJAS RENNER'],
    ['MGLU3', ' - MAGAZ LUIZA'],
    ['MRFG3', ' - MARFRIG'],
    ['MRVE3', ' - MRV'],
    ['MULT3', ' - MULTIPLAN'],
    ['NATU3', ' - NATURA'],
    ['ODPV3', ' - ODONTOPREV'],
    ['PCAR3', ' - P.ACUCAR-CBD'],
    ['PETR3', ' - PETROBRAS'],
    ['PSSA3', ' - PORTO SEGURO'],
    ['QUAL3', ' - QUALICORP'],
    ['RADL3', ' - RAIADROGASIL'],
    ['RAIL3', ' - RUMO'],
    ['RENT3', ' - LOCALIZA'],
    ['SBSP3', ' - SABESP'],
    ['SULA3', ' - SUL AMERICA'],
    ['SUZB3', ' - SUZANO'],
    ['TAEE3', ' - TAESA'],
    ['TIMS3', ' - TIM PARTICIPACOES'],
    ['TOTS3', ' - TOTVS'],
    ['UGPA3', ' - ULTRAPAR'],
    ['USIM3', ' - USIMINAS'],
    ['VALE3', ' - VALE'],
    ['VIVT3', ' - TELEF BRASIL'],
    ['BHIA3', ' - GRUPO CASAS BAHIA'],
    ['WEGE3', ' - WEG'],
  ];

}

export const stocks: StockEntity[] = 
[
  {
    id: "EGIE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ENGIE BRASIL",
    
  },
  {
    id: "PETR3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "PETROBRAS",
    
  },
  {
    id: "VALE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "VALE",
    
  },
  {
    id: "B3SA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "B3",
    score: "GOOD",
    
  },
  {
    id: "ABEV3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AMBEV S/A",
    score: "GOOD",
    
  },
  {
    id: "COGN3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "COGNA ON",
    segmentoEmpresa: "Serviços Educacionais",
    
  },
  {
    id: "VIIA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CASAS BAHIA",
    segmentoEmpresa: "Eletrodomésticos",
    
  },
  {
    id: "BBDC3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRADESCO",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "BBAS3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRASIL",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "MGLU3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "MAGAZ LUIZA",
    segmentoEmpresa: "Eletrodomésticos",
    
  },
  {
    id: "ITUB3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ITAUUNIBANCO",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "CIEL3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CIELO",
    
  },
  {
    id: "ELET3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ELETROBRAS",
    
  },
  {
    id: "CPLE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "COPEL",
    
  },
  {
    id: "ITSA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ITAUSA",
    
  },
  {
    id: "HAPV3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "HAPVIDA",
    segmentoEmpresa: "Serv.Méd.Hospit..Análises e Diagnósticos",
    
  },
  {
    id: "BPAC3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BTGP BANCO",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "BRFS3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRF SA",
    
  },
  {
    id: "RENT3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "LOCALIZA",
    segmentoEmpresa: "Aluguel de carros",
    
  },
  {
    id: "WEGE3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "WEG",
    segmentoEmpresa: "Motores . Compressores e Outros",
    score: "GOOD",
    
  },
  {
    id: "CMIG3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CEMIG",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "CSNA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SID NACIONAL",
    
  },
  {
    id: "GGBR3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GERDAU",
    
  },
  {
    id: "CVCB3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CVC BRASIL",
    segmentoEmpresa: "Viagens e Turismo",
    
  },
  {
    id: "CCRO3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CCR SA",
    segmentoEmpresa: "Exploração de Rodovias",
    
  },
  {
    id: "CYRE3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CYRELA REALT",
    segmentoEmpresa: "Incorporações",
    
  },
  {
    id: "GNDI3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "INTERMEDICA",
    segmentoEmpresa: "Serv.Méd.Hospit..Análises e Diagnósticos",
    
  },
  {
    id: "EQTL3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "EQUATORIAL",
    segmentoEmpresa: "Energia Elétrica",
    score: "FAIR",
    
  },
  {
    id: "GOAU3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GERDAU MET",
    segmentoEmpresa: "Siderurgia",
    
  },
  {
    id: "JBSS3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "JBS",
    segmentoEmpresa: "Carnes e Derivados",
    
  },
  {
    id: "KLBN3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "KLABIN S/A",
    segmentoEmpresa: "Papel e Celulose",
    
  },
  {
    id: "LAME3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "LOJAS AMERIC",
    segmentoEmpresa: "Produtos Diversos",
    
  },
  {
    id: "RADL3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "RAIADROGASIL",
    segmentoEmpresa: "Medicamentos e Outros Produtos",
    
  },
  {
    id: "RAIL3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "RUMO S.A.",
    segmentoEmpresa: "Transporte Ferroviário",
    
  },
  {
    id: "MRFG3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "MARFRIG",
    segmentoEmpresa: "Carnes e Derivados",
    
  },
  {
    id: "SUZB3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SUZANO S.A.",
    segmentoEmpresa: "Papel e Celulose",
    
  },
  {
    id: "SBSP3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SABESP",
    segmentoEmpresa: "Água e Saneamento",
    
  },
  {
    id: "SULA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SUL AMERICA",
    segmentoEmpresa: "Seguradoras",
    
  },
  {
    id: "UGPA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ULTRAPAR",
    segmentoEmpresa: "Exploração. Refino e Distribuição",
    
  },
  {
    id: "TOTS3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TOTVS",
    segmentoEmpresa: "Programas e Serviços",
    
  },
  {
    id: "USIM3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "USIMINAS",
    segmentoEmpresa: "Siderurgia",
    
  },
  {
    id: "TAEE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TAESA",
    score: "GOOD",
    
  },
  {
    id: "AERI3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AERISENERGIA",
    
  },
  {
    id: "SLCE3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SLC AGRICOLA",
    segmentoEmpresa: "Agricultura",
    
  },
  {
    id: "ROMI3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "INDS ROMI",
    segmentoEmpresa: "Máq. e Equip. Industriais",
    score: "GOOD",
    
  },
  {
    id: "AGXY3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AGROGALAXY",
    segmentoEmpresa: "Agricultura",
    
  },
  {
    id: "ARZZ3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AREZZO CO",
    segmentoEmpresa: "Tecidos. Vestuário e Calçados",
    
  },
  {
    id: "BRSR3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BANRISUL",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "WLMM3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "WLM IND COM",
    segmentoEmpresa: "Material de Transporte",
    
  },
  {
    id: "ANIM3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ANIMA",
    segmentoEmpresa: "Serviços Educacionais",
    
  },
  {
    id: "JSLG3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "JSL",
    segmentoEmpresa: "Transporte Rodoviário",
    
  },
  {
    id: "EPAR3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "EMBPAR-SA",
    segmentoEmpresa: "Holdings Diversificadas",
    
  },
  {
    id: "BOAS3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BOA VISTA",
    segmentoEmpresa: "Serviços Financeiros Diversos",
    
  },
  {
    id: "ENJU3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ENJOEI",
    segmentoEmpresa: "Programas e Serviços",
    
  },
  {
    id: "BLUT3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "B TECH EQI",
    segmentoEmpresa: "Holdings Diversificadas",
    
  },
  {
    id: "BRIT3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRISANET",
    segmentoEmpresa: "Telecomunicações",
    
  },
  {
    id: "BRAP3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRADESPAR",
    segmentoEmpresa: "Minerais Metálicos",
    
  },
  {
    id: "CMIN3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CSN MINERACA",
    segmentoEmpresa: "Minerais Metálicos",
    
  },
  {
    id: "AESB3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AES BRASIL",
    
  },
  {
    id: "TRPL3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TRAN PAULIST",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "TIMS3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TIM PART S/A",
    segmentoEmpresa: "Telecomunicações",
    
  },
  {
    id: "GGPS3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GPS",
    segmentoEmpresa: "Logística",
    
  },
  {
    id: "WHRL3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "WHIRLPOOL",
    segmentoEmpresa: "Eletrodomésticos",
    
  },
  {
    id: "MAPT3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CEMEPE",
    segmentoEmpresa: "Outros",
    
  },
  {
    id: "EMBR3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "EMBRAER",
    segmentoEmpresa: "Material Aeronáutico e de Defesa",
    
  },
  {
    id: "NGRD3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "NEOGRID",
    
  },
  {
    id: "PETZ3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "PETZ",
    segmentoEmpresa: "Produtos Diversos",
    
  },
  {
    id: "ENEV3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ENEVA",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "ALPA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ALPARGATAS",
    
  },
  {
    id: "BBSE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BBSEGURIDADE",
    segmentoEmpresa: "Seguradoras",
    score: "FAIR",
    
  },
  {
    id: "BIDI4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BANCO INTER",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "BBDC4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRADESCO",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "BEEF3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "MINERVA",
    segmentoEmpresa: "Carnes e Derivados",
    score: "FAIR",
    
  },
  {
    id: "BIDI11",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BANCO INTER",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "AZUL4",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AZUL",
    segmentoEmpresa: "Transporte Aéreo",
    
  },
  {
    id: "BRAP4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRADESPAR",
    segmentoEmpresa: "Minerais Metálicos",
    
  },
  {
    id: "BPAC11",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BTGP BANCO",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "BRML3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BR MALLS PAR",
    segmentoEmpresa: "Exploração de Imóveis",
    score: "FAIR",
    
  },
  {
    id: "CGRA4",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GRAZZIOTIN",
    segmentoEmpresa: "Tecidos. Vestuário e Calçados",
    
  },
  {
    id: "CMIG4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CEMIG",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "CRFB3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CARREFOUR BR",
    score: "FAIR",
    
  },
  {
    id: "CPFE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CPFL ENERGIA",
    segmentoEmpresa: "Energia Elétrica",
    score: "GOOD",
    
  },
  {
    id: "CSMG3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "COPASA",
    segmentoEmpresa: "Água e Saneamento",
    score: "EXCELLENT",
    
  },
  {
    id: "CSAN3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "COSAN",
    segmentoEmpresa: "Exploração. Refino e Distribuição",
    score: "FAIR",
    
  },
  {
    id: "ECOR3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ECORODOVIAS",
    score: "FAIR",
    
  },
  {
    id: "DIRR3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "DIRECIONAL",
    segmentoEmpresa: "Incorporações",
    score: "GOOD",
    
  },
  {
    id: "DASA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "DASA",
    segmentoEmpresa: "Serv.Méd.Hospit..Análises e Diagnósticos",
    score: "FAIR",
    
  },
  {
    id: "FLRY3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "FLEURY",
    score: "FAIR",
    
  },
  {
    id: "ENBR3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ENERGIAS BR",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "ENGI11",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ENERGISA",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "EZTC3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "EZTEC",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "GOAU4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GERDAU MET",
    segmentoEmpresa: "Siderurgia",
    
  },
  {
    id: "GGBR4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GERDAU",
    segmentoEmpresa: "Siderurgia",
    
  },
  {
    id: "HYPE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "HYPERA",
    score: "GOOD",
    
  },
  {
    id: "GOLL4",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GOL",
    segmentoEmpresa: "Transporte Aéreo",
    
  },
  {
    id: "HGTX3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CIA HERING",
    segmentoEmpresa: "Vestuário",
    score: "FAIR",
    
  },
  {
    id: "IGTA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "IGUATEMI",
    segmentoEmpresa: "Exploração de Imóveis",
    score: "FAIR",
    
  },
  {
    id: "IRBR3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "IRBBRASIL RE",
    segmentoEmpresa: "Seguradoras",
    score: "FAIR",
    
  },
  {
    id: "ITSA4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ITAUSA",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "ITUB4",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ITAUUNIBANCO",
    segmentoEmpresa: "Bancos",
    
  },
  {
    id: "KLBN11",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "KLABIN S/A",
    segmentoEmpresa: "Papel e Celulose",
    
  },
  {
    id: "LCAM3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "LOCAMERICA",
    segmentoEmpresa: "Aluguel de carros",
    score: "FAIR",
    
  },
  {
    id: "LEVE3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "METAL LEVE",
    segmentoEmpresa: "Automóveis e Motocicletas",
    score: "GOOD",
    
  },
  {
    id: "LREN3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "LOJAS RENNER",
    segmentoEmpresa: "Tecidos. Vestuário e Calçados",
    score: "FAIR",
    
  },
  {
    id: "LINX3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "LINX",
    segmentoEmpresa: "Programas e Serviços",
    score: "FAIR",
    
  },
  {
    id: "LIGT3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "LIGHT S/A",
    segmentoEmpresa: "Energia Elétrica",
    score: "FAIR",
    
  },
  {
    id: "MRVE3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "MRV",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "ODPV3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ODONTOPREV",
    segmentoEmpresa: "Serv.Méd.Hospit..Análises e Diagnósticos",
    score: "FAIR",
    
  },
  {
    id: "MULT3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "MULTIPLAN",
    segmentoEmpresa: "Exploração de Imóveis",
    score: "EXCELLENT",
    
  },
  {
    id: "PCAR3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "P.ACUCAR-CBD",
    segmentoEmpresa: "Alimentos",
    score: "FAIR",
    
  },
  {
    id: "PSSA3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "PORTO SEGURO",
    segmentoEmpresa: "Seguradoras",
    score: "GOOD",
    
  },
  {
    id: "QUAL3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "QUALICORP",
    segmentoEmpresa: "Serv.Méd.Hospit..Análises e Diagnósticos",
    score: "FAIR",
    
  },
  {
    id: "PETR4",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "PETROBRAS",
    segmentoEmpresa: "Exploração. Refino e Distribuição",
    
  },
  {
    id: "SULA11",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SUL AMERICA",
    segmentoEmpresa: "Seguradoras",
    
  },
  {
    id: "TAEE11",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TAESA",
    segmentoEmpresa: "Energia Elétrica",
    
  },
  {
    id: "VIVT3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TELEF BRASIL",
    segmentoEmpresa: "Telecomunicações",
    score: "FAIR",
    
  },
  {
    id: "VIVT4",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TELEF BRASIL",
    segmentoEmpresa: "Telecomunicações",
    
  },
  {
    id: "BRKM3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRASKEM",
    segmentoEmpresa: "Petroquímicos",
    score: "FAIR",
    
  },
  {
    id: "CESP3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CESP",
    segmentoEmpresa: "Energia Elétrica",
    score: "GOOD",
    
  },
  {
    id: "ENGI3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ENERGISA",
    segmentoEmpresa: "Energia Elétrica",
    score: "FAIR",
    
  },
  {
    id: "CGRA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "GRAZZIOTIN",
    segmentoEmpresa: "Tecidos. Vestuário e Calçados",
    score: "FAIR",
    
  },
  {
    id: "AMER3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AMERICANAS",
    segmentoEmpresa: "Produtos Diversos",
    score: "BAD",
    
  },
  {
    id: "CXSE3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CAIXA SEGURI",
    segmentoEmpresa: "Corretoras de Seguros",
    score: "GOOD",
    
  },
  {
    id: "SANB3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SANTANDER BR",
    segmentoEmpresa: "Bancos",
    score: "FAIR",
    
  },
  {
    id: "SMTO3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SAO MARTINHO",
    segmentoEmpresa: "Açucar e Alcool",
    score: "GOOD",
    
  },
  {
    id: "AGRO3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "BRASILAGRO",
    segmentoEmpresa: "Agricultura",
    score: "GOOD",
    
  },
  {
    id: "TESA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TERRA SANTA",
    segmentoEmpresa: "Agricultura",
    score: "FAIR",
    
  },
  {
    id: "AALR3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "ALLIAR",
    segmentoEmpresa: "Serv.Méd.Hospit..Análises e Diagnósticos",
    score: "FAIR",
    
  },
  {
    id: "TIET3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: false,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "AES TIETE E",
    segmentoEmpresa: "Energia Elétrica",
    score: "FAIR",
    
  },
  {
    id: "TEND3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TENDA",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "EVEN3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "EVEN",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "JHSF3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "JHSF PART",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "HBOR3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "HELBOR",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "TCSA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TECNISA",
    segmentoEmpresa: "Incorporações",
    score: "FAIR",
    
  },
  {
    id: "RANI3",
    estaEmSetorPerene: true,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "IRANI",
    segmentoEmpresa: "Embalagens",
    score: "GOOD",
    
  },
  {
    id: "MDIA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "M.DIASBRANCO",
    segmentoEmpresa: "Alimentos Diversos",
    score: "FAIR",
    
  },
  {
    id: "TRIS3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "TRISUL",
    segmentoEmpresa: "Incorporações",
    score: "GOOD",
    
  },
  {
    id: "PRIO3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: true,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: true,
    possuiBomNivelMargemLiquida: true,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: false,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "PETRORIO",
    segmentoEmpresa: "Exploração. Refino e Distribuição",
    score: "GOOD",
    
  },
  {
    id: "YDUQ3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "YDUQS PART",
    segmentoEmpresa: "Serviços Educacionais",
    score: "FAIR",
    
  },
  {
    id: "SEER3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "SER EDUCA",
    segmentoEmpresa: "Serviços Educacionais",
    score: "FAIR",
    
  },
  {
    id: "CSED3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: true,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: true,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CRUZEIRO EDU",
    segmentoEmpresa: "Serviços Educacionais",
    score: "FAIR",
    
  },
  {
    id: "BHIA3",
    estaEmSetorPerene: false,
    estaForaDeRecuperacaoJudicial: true,
    possuiBomNivelRetornoSobrePatrimonio: false,
    possuiBomNivelCrescimentoLucroNosUltimos5Anos: false,
    possuiBomNivelMargemLiquida: false,
    possuiBomNivelMargemEbit: false,
    possuiBomNivelDeCapacidadeDeQuitarDividaNoCurtoPrazo: false,
    possuiBomNivelDividaLiquidaSobrePatrimonioLiquido: true,
    possuiBomPrecoEmRelacaoAoValorPatrimonial: true,
    possuiNegociacaoAtiva: true,
    nomeEmpresa: "CASAS BAHIA",
    segmentoEmpresa: "Eletrodomésticos",
    
  }
]
;
